### ISSUE TITLE
listlib fails on macos

### ISSUE THREAD

**Issue by jvehent** [mozilla/masche#31] opened 2015-05-13 16:47 UTC
Invoking listlib on macos results in a panic that seems to be related to C code. This issue surfaced in MIG modules tests, but can be reproduced using the listlib example:

```
julien@Juliens-Mac-mini[16:45:54]:examples [master -]$ sudo ./listlibs -r libssl
Password:
listlibs(27868,0x7fff77910180) malloc: *** error for object 0xe000000000000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff8ef25212
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0x4000ef0, 0xc2080559c8, 0xc200000000)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/cgocall.go:130 +0xf5 fp=0xc2080559a8 sp=0xc208055980
github.com/mozilla/masche/listlibs._Cfunc_free_loaded_libraries_list(0x4600040, 0xe000000000000000)
        /Users/julien/.go/src/github.com/mozilla/masche/listlibs/:32 +0x45 fp=0xc2080559c8 sp=0xc2080559a8
github.com/mozilla/masche/listlibs.listLoadedLibraries(0x42679f8, 0xc20802a2b0, 0xc208074000, 0x92, 0x93, 0x0, 0x0, 0x41e2e30, 0x0, 0x0)
        /Users/julien/.go/src/github.com/mozilla/masche/listlibs/listlibs_darwin.go:56 +0x4ef fp=0xc208055ad0 sp=0xc2080559c8
github.com/mozilla/masche/listlibs.ListLoadedLibraries(0x42679f8, 0xc20802a2b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/julien/.go/src/github.com/mozilla/masche/listlibs/listlibs.go:11 +0x89 fp=0xc208055b28 sp=0xc208055ad0
github.com/mozilla/masche/listlibs.GetMatchingLoadedLibraries(0x42679f8, 0xc20802a2b0, 0xc20805e0a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/julien/.go/src/github.com/mozilla/masche/listlibs/listlibs.go:18 +0xa0 fp=0xc208055c00 sp=0xc208055b28
main.findProcWithLib(0xc20805e0a0, 0xc208072000, 0x63, 0x80, 0xc20800a360, 0x0, 0x0, 0x41e2e30, 0x0, 0x0)
        /Users/julien/Code/masche/examples/listlibs.go:61 +0x180 fp=0xc208055d30 sp=0xc208055c00
main.main()
        /Users/julien/Code/masche/examples/listlibs.go:35 +0x443 fp=0xc208055f98 sp=0xc208055d30
runtime.main()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:63 +0xf3 fp=0xc208055fe0 sp=0xc208055f98
runtime.goexit()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208055fe8 sp=0xc208055fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1

rax     0x0
rbx     0x6
rcx     0x7fff5fbffba8
rdx     0x0
rdi     0x707
rsi     0x6
rbp     0x7fff5fbffbd0
rsp     0x7fff5fbffba8
r8      0x7fff7790f278
r9      0x0
r10     0x20000000
r11     0x206
r12     0x4225000
r13     0x4255000
r14     0x7fff77910180
r15     0x1
rip     0x7fff8ef25212
rflags  0x206
cs      0x7
fs      0x0
gs      0x0
```

**Comment by alcuadrado** [comment] 2015-05-13 17:23
I'll be terribly busy until 05/22, but I'll try to take a look at this if I
get some spare time, or ping me after that date if this is still open.

**Comment by jvehent** [comment] 2015-06-02 11:55
@alcuadrado: Any chance that you could investigate this issue in the next couple of weeks? I'd like to deploy masche on some macos hosts for testing sometime in june/july.

**Comment by mvanotti** [comment] 2015-06-03 17:36
Hi,

I think @alcuadrado is very busy with school these weeks. I might be able to take a look at it @jvehent, but I would need access to a Mac OS machine. Do you still have that mac available?

**Comment by alcuadrado** [comment] 2015-06-03 18:25
Hi Marco and Julien,

I'm kinda busy, but I guess I can check this on Saturday. Of course, if you
wanna take a look at it Marco, it's much better for me.

**Comment by mvanotti** [comment] 2015-06-05 16:59
Don't worry. If I can't fix it I will ask you to take a look at it.

**Comment by jvehent** [comment] 2015-08-26 20:56
Hey guys, it's still breaking and getting in the way of updating the client on macos. Do you think you could take a look?

**Comment by alcuadrado** [comment] 2015-08-28 14:40
Marco, I'll be out of town until 09/10, can you take a look at this?

**Comment by mvanotti** [comment] 2015-08-29 02:00
Taking a look at it right now. So far I couldn't reproduce the issue. Waiting to get sudo privileges to try running the command as root.

**Comment by mvanotti** [comment] 2015-08-29 02:51
Talked with @jvehent , we were not able to reproduce it on his machine (Yosemite), I tried to reproduce it in another machine running Yosemite and I couldn't.

Apparently this bug was noticed on Mountain Lion, so @jvehent will try to reproduce it in a Mac running that OS.

**Comment by jvehent** [comment] 2015-09-01 13:31
I can't reproduce it on mountain lion easier... 

```xml
# grep -A 1 ProductVersion /System/Library/CoreServices/SystemVersion.plist
        <key>ProductVersion</key>
        <string>10.7.2</string>
```
```bash
# go version
go version go1.5 darwin/amd64
# go get github.com/mozilla/masche/listlibs
# cd $GOPATH/src/github.com/mozilla/masche/examples
# go build listlibs.go
# ./listlibs -r libssl
Processes matching: libssl
[91] /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow
        /usr/lib/libssl.0.9.8.dylib
[75] /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/Resources/usbmuxd
        /usr/lib/libssl.0.9.7.dylib
[32] /usr/libexec/opendirectoryd
        /usr/lib/libssl.0.9.8.dylib
[198] /System/Library/CoreServices/ManagedClient.app/Contents/MacOS/ManagedClient
        /usr/lib/libssl.0.9.8.dylib
[94] /System/Library/PrivateFrameworks/Heimdal.framework/Helpers/kdc
        /usr/lib/libssl.0.9.8.dylib
[201] /System/Library/CoreServices/SecurityAgent.app/Contents/MacOS/SecurityAgent
        /usr/lib/libssl.0.9.8.dylib
[30] /usr/libexec/UserEventAgent
        /usr/lib/libssl.0.9.8.dylib
[4211] /usr/sbin/ocspd
        /usr/lib/libssl.0.9.8.dylib
[4192] /usr/sbin/sshd
        /usr/lib/libssl.0.9.8.dylib
# cd ..
# make
go get -u github.com/mozilla/masche/process
go get -u github.com/mozilla/masche/memsearch
go get -u github.com/mozilla/masche/memaccess
go get -u github.com/mozilla/masche/listlibs
make -C test/tools test64
gcc -Wall -Wextra -pedantic -std=c99 -O0 known_byte_sequences.c -o test
go test ./memaccess ./memsearch ./process ./common
ok      github.com/mozilla/masche/memaccess     8.353s
ok      github.com/mozilla/masche/memsearch     3.952s
ok      github.com/mozilla/masche/process       0.055s
?       github.com/mozilla/masche/common        [no test files]
make -C test/tools test32
gcc -Wall -Wextra -pedantic -std=c99 -O0 known_byte_sequences.c -m32 -o test
go test ./memaccess ./memsearch ./process ./common
ok      github.com/mozilla/masche/memaccess     9.450s
ok      github.com/mozilla/masche/memsearch     5.421s
ok      github.com/mozilla/masche/process       0.070s
?       github.com/mozilla/masche/common        [no test files]
```

**Comment by jvehent** [comment] 2015-09-01 13:37
Ha! I can reproduce it in `go 1.4.2`.

```bash
# go version
go version go1.4.2 darwin/amd64
# go build listlibs.go
# ./listlibs -r libssl
listlibs(18383,0x7fff7b79b960) malloc: *** error for object 0x5000000000000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
SIGABRT: abort
PC=0x7fff90190ce2
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall_errno(0xd4250, 0xc2080599c8, 0xc200000000)
        /usr/local/go/src/runtime/cgocall.go:130 +0xf5 fp=0xc2080599a8 sp=0xc208059980
github.com/mozilla/masche/listlibs._Cfunc_free_loaded_libraries_list(0x600040, 0x5000000000000000)
        /var/root/go/src/github.com/mozilla/masche/listlibs/:30 +0x45 fp=0xc2080599c8 sp=0xc2080599a8
github.com/mozilla/masche/listlibs.listLoadedLibraries(0x2669f8, 0xc2080282b0, 0xc20806c000, 0x27, 0x27, 0x0, 0x0, 0x1eb430, 0x0, 0x0)
        /var/root/go/src/github.com/mozilla/masche/listlibs/listlibs_darwin.go:56 +0x4ef fp=0xc208059ad0 sp=0xc2080599c8
github.com/mozilla/masche/listlibs.ListLoadedLibraries(0x2669f8, 0xc2080282b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /var/root/go/src/github.com/mozilla/masche/listlibs/listlibs.go:11 +0x89 fp=0xc208059b28 sp=0xc208059ad0
github.com/mozilla/masche/listlibs.GetMatchingLoadedLibraries(0x2669f8, 0xc2080282b0, 0xc20805c0a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /var/root/go/src/github.com/mozilla/masche/listlibs/listlibs.go:18 +0xa0 fp=0xc208059c00 sp=0xc208059b28
main.findProcWithLib(0xc20805c0a0, 0xc20806e000, 0x31, 0x40, 0xc20800a3c0, 0x0, 0x0, 0x1eb430, 0x0, 0x0)
        /var/root/go/src/github.com/mozilla/masche/examples/listlibs.go:61 +0x180 fp=0xc208059d30 sp=0xc208059c00
main.main()
        /var/root/go/src/github.com/mozilla/masche/examples/listlibs.go:35 +0x443 fp=0xc208059f98 sp=0xc208059d30
runtime.main()
        /usr/local/go/src/runtime/proc.go:63 +0xf3 fp=0xc208059fe0 sp=0xc208059f98
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc208059fe8 sp=0xc208059fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

rax     0x0
rbx     0x6
rcx     0x7fff5fbffb38
rdx     0x0
rdi     0x707
rsi     0x6
rbp     0x7fff5fbffb60
rsp     0x7fff5fbffb38
r8      0x7fff7b798fb8
r9      0x7fff91bf4230
r10     0x7fff90190d0a
r11     0xffffff80002d8220
r12     0x254000
r13     0x1
r14     0x7fff7b79b960
r15     0x1
rip     0x7fff90190ce2
rflags  0x246
cs      0x7
fs      0x0
gs      0x0
```

So, I'm not sure if this is worth investigating since MIG now requires Go1.5 to build (because we use the vendor experiment). Take a look if you want, otherwise feel free to close this issue.

**Comment by mvanotti** [comment] 2015-09-01 16:27
I was able to reproduce it with Go 1.5. It happens only sometimes. I will look into it.

**Comment by alcuadrado** [comment] 2015-09-01 17:24
Good work marco!

**Comment by mvanotti** [comment] 2015-09-01 17:46
Almost! :P I don't have my computer with me so I asked @alcuadrado  to do the commit for me, but I made a mistake telling him where to move the line to.

Commit c1ce137c does not fix the issue. You still have to move the defer further down, after the call to  ` C.list_loaded_libraries`

The problem is that defer params are evaluated when the defer is executed, not at the end of the function [More from Effective Go] (https://golang.org/doc/effective_go.html#defer). So `*count` and `*clibs` keep their original values instead of the values that are loaded after calling ` C.list_loaded_libraries`.

Moving the defer after that call would fix the issue.

**Comment by mvanotti** [comment] 2015-09-01 17:58
Success! :dancer:

**Comment by mvanotti** [comment] 2015-09-01 18:02
@jvehent  I'm closing the issue, if you encounter the same message whilst running listlibs feel free to reopen.

**Closed by mvanotti** 2015-09-01 18:02 UTC

**Comment by jvehent** [comment] 2015-09-01 18:12
Awesome! Thanks for fixing it :+1:
